# Generated by Django 4.1.3 on 2022-11-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loggedin',
            field=models.BooleanField(default=False),
        ),
    ]
